# Use official Node.js image
FROM node:20-alpine

# Set working directory inside container
WORKDIR /app

# Copy files from host into container
COPY . .

# Command to run your app
CMD ["node", "Hello.js"]
